=== ArpadVS/XML_tim14_2019-Publication/publications/publications/src/main/resources/data/xsd/CoverLetter.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="https://github.com/ArpadVS/XML_tim14_2019-Publication"
    xmlns:cl="https://github.com/ArpadVS/XML_tim14_2019-Publication"
    xmlns:cmn="https://github.com/ArpadVS/XML_tim14_2019-Publication">
    <xs:include schemaLocation="Shared.xsd"/>
    <xs:element name="Cover_letter">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="sender_contact" type="cl:TContact"/>
                <xs:element name="employer_contact" type="cl:TContact"/>
                <xs:element name="body" type="cl:TBody"/>
            </xs:sequence>
            <xs:attribute name="date" type="xs:date"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="TContact">
        <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element default="000-000-0000" name="Phone_number">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\d{3}-\d{3}-\d{4}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Location"/>
            <xs:element name="Email">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[a-z]+@[a-z]+\.[a-z]{2,4}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TBody">
        <xs:sequence>
            <xs:element name="Paragraphs" type="cl:TParagraphs"/>
            <xs:element name="Thanksgiving" type="xs:string"/>
            <xs:element name="Closure" type="cl:TClosure"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TClosure">
        <xs:sequence>
            <xs:element name="Compliment" type="xs:string"/>
            <xs:element name="Signature" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== ArpadVS/XML_tim14_2019-Publication/publications/publications/src/main/resources/data/xml/CoverLetter1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Cover_letter xmlns="https://github.com/ArpadVS/XML_tim14_2019-Publication"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="https://github.com/ArpadVS/XML_tim14_2019-Publication file:/C:/Users/Marieta/XML_workspace/111projekat-tim14/XML_tim14_2019-Publication/publications/publications/src/main/resources/data/xsd/CoverLetter.xsd">
    <sender_contact>
        <Name>Name0</Name>
        <Phone_number>000-000-0000</Phone_number>
        <Location>
        </Location>
        <Email>a@a.aa</Email>
    </sender_contact>
    <employer_contact>
        <Name>Name1</Name>
        <Phone_number>000-000-0000</Phone_number>
        <Location>
        </Location>
        <Email>a@a.aa</Email>
    </employer_contact>
    <body>
        <Paragraphs>
            <Paragraph/>
            <Paragraph/>
        </Paragraphs>
        <Thanksgiving>Thanksgiving0</Thanksgiving>
        <Closure>
            <Compliment>Compliment0</Compliment>
            <Signature>Signature0</Signature>
        </Closure>
    </body>
</Cover_letter>

=== ArpadVS/XML_tim14_2019-Publication/publications/publications/src/main/resources/data/xml/letter2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Cover_letter xmlns="https://github.com/ArpadVS/XML_tim14_2019-Publication"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="https://github.com/ArpadVS/XML_tim14_2019-Publication ../xsd/CoverLetter.xsd">
    <sender_contact>
        <Name>Name0</Name>
        <Phone_number>000-000-0000</Phone_number>
        <Location>Location0</Location>
        <Email>a@a.aa</Email>
    </sender_contact>
    <employer_contact>
        <Name>Name1</Name>
        <Phone_number>000-000-0000</Phone_number>
        <Location>
        </Location>
        <Email>a@a.aa</Email>
    </employer_contact>
    <body>
        <Paragraphs>Paragraphs0</Paragraphs>
        <Paragraphs>Paragraphs1</Paragraphs>
        <Thanksgiving>Thanksgiving0</Thanksgiving>
        <Closure>
            <Compliment>Compliment0</Compliment>
            <Signature>Signature0</Signature>
        </Closure>
    </body>
</Cover_letter>
